apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: $CIRCLE_BRANCH
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/fluxcd/repositories/infra-repo/apps/$CIRCLE_BRANCH
  prune: true
  wait: true
  timeout: 5m0s